version: "3.8"
networks:
  blackjack-deploy:
    driver: bridge

services:
  client:
    container_name: blackjack-client
    image: blackjack-client
    ports:
      - "8000:80"
    depends_on:
      - app
    networks:
      - blackjack-deploy
  
  app:
    container_name: blackjack.server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__ContainerDatabase=Host=db;Port=5432;Database=blackjack;Username=postgres;Password=1234;Include Error Detail=true
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - blackjack-deploy
      
  db:
    container_name: blackjack.database
    image: postgres:16
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: blackjack
    networks:
      - blackjack-deploy